#drv config band
#2.4G band should set 2
#5G band should set 5
#both should set 6
cfg_band=6
cfg_txpowlimit=20
cfg_ampdu_subframes=16
cfg_dynamic_bw=0
cfg_wifi_bt_coexist_support=0
cfg_mac_mode=5
cfg_burst_ack=1
cfg_40Msupport=1
cfg_txaggr=1
cfg_rxaggr=1
cfg_txamsdu=1
cfg_retry_limit=7
cfg_latency_retry_enable=0
cfg_listen_interval=1
cfg_uapsd=0
cfg_disable_ratecontrol=0
cfg_disable_fw_sleep=1
